import type { Metadata } from "next";
import "./globals.scss";
import HeaderWrapper from "@/components/headerWrapper";
import BackgroundMusic from "@/components/BackgroundMusic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HeaderWrapper />
        {children}
        <BackgroundMusic />
      </body>
    </html>
  );
}
